# 07_h3_cwd_dry_elder.R
# Validates whether the CWDmax contrast reported by Hahm et al. (2019)
# between Elder Creek (Coastal Belt) and Dry Creek (Central Belt) is
# recoverable in the 30 m CWDmax product generated by the GEE workflow.
# Extracts CWDmax for all pixels within the two hand-digitised catchment
# polygons. This is a validation test against published findings, not a
# novel hypothesis test.

# ---- Setup ------------------------------------------------------------------

library(terra)
library(sf)
library(dplyr)
library(ggplot2)
library(readr)
library(here)

# add_boxplot_n() adds per-group n to the boxplot below.
# save_fig() writes each figure to fig/ as PDF and PNG (see R/save_fig.R).
source(here("R", "add_boxplot_n.R"))
source(here("R", "save_fig.R"))

# No LANID filter here, unlike the other Eel River scripts: both catchments
# are forested headwaters with no irrigated land, so the filter would be a
# no-op.

# Load raster
r_cwd <- terra::rast(here("data", "eel_9ref.tif"))[["cwd_max"]]

# ---- Load hand-drawn catchment polygons -------------------------------------
# Hand-digitised catchment outlines, delivered in NAD83 Contiguous USA Albers
# (parameter-identical to EPSG:5070 / cfg.EXPORT_CRS), so no reprojection is
# expected -- but we transform explicitly rather than relying on terra's
# implicit handling (Kap. 12.6: always confirm CRS alignment before a
# raster-vector operation).
poly_elder <- sf::st_read(here("data-raw", "elder_creek_polygon.shp"), quiet = TRUE) |>
  dplyr::mutate(site = "Elder Creek")
poly_dry <- sf::st_read(here("data-raw", "dry_creek_polygon.shp"), quiet = TRUE) |>
  dplyr::mutate(site = "Dry Creek")

polys <- dplyr::bind_rows(poly_elder, poly_dry) |>
  dplyr::select(site) |>
  sf::st_transform(crs = terra::crs(r_cwd))

# ---- Extract all pixels falling within each polygon -------------------------
# Default terra::extract() behaviour: a pixel is included if its centre
# falls inside the polygon (no area-weighting of edge pixels).
df <- terra::extract(r_cwd, terra::vect(polys)) |>
  dplyr::mutate(
    site = factor(polys$site[ID], levels = c("Elder Creek", "Dry Creek"))
  ) |>
  dplyr::filter(!is.na(cwd_max))

readr::write_csv(df, here("data", "h3_cwd_validation.csv"))

# ---- Boxplot ------------------------------------------------------------------
p <- ggplot(df, aes(x = site, y = cwd_max)) +
  geom_boxplot(fill = "grey70", outlier.size = 0.3, outlier.alpha = 0.2) +
  labs(
    x = NULL,
    y = expression(CWD[max] ~ "[mm]")
  ) +
  theme_classic() +
  theme(legend.position = "none")

# Add per-group n label.
p <- p + add_boxplot_n(df, "site", "cwd_max")

print(p)

save_fig(p, "h3_elder_dry", width = 12, height = 10)