# 07_h3_cwd_dry_elder.R
# Validates whether the CWDmax contrast reported by Hahm et al. (2019)
# between Elder Creek (Coastal Belt) and Dry Creek (Central Belt) is
# recoverable in the 30 m CWDmax product generated by the GEE workflow.
# Extracts CWDmax for all pixels within the two catchment polygons and
# reports them next to a satellite map of the two sites.

# ---- Setup ------------------------------------------------------------------

library(terra)
library(sf)
library(dplyr)
library(ggplot2)
library(readr)
library(maptiles)
library(tidyterra)
library(ggspatial)
library(cowplot)
library(here)

# add_boxplot_n() adds per-group n to the boxplot below.
source(here("R", "add_boxplot_n.R"))
source(here("R", "save_fig.R"))

# Panel geometry (cm). The map keeps the size of the focus-region maps,
# the boxplot is fitted to its height.
map_w_cm   <- 16
box_w_cm   <- 12
panel_h_cm <- 12

# No LANID filter here because the catchments do not feature irrigated pixels

# Load raster
r_cwd <- terra::rast(here("data", "eel_9ref.tif"))[["cwd_max"]]

# ---- Load hand-drawn catchment polygons -------------------------------------
# Outlines are in NAD83 CONUS Albers (parameter-identical to the raster's
# EPSG:5070), so this transform is effectively a no-op. It is done explicitly to
# guarantee CRS alignment before the extract
poly_elder <- sf::st_read(here("data-raw", "elder_creek_polygon.shp"), quiet = TRUE) |>
  dplyr::mutate(site = "Elder Creek")
poly_dry <- sf::st_read(here("data-raw", "dry_creek_polygon.shp"), quiet = TRUE) |>
  dplyr::mutate(site = "Dry Creek")

polys <- dplyr::bind_rows(poly_elder, poly_dry) |>
  dplyr::select(site) |>
  sf::st_transform(crs = terra::crs(r_cwd))

# ---- Extract all pixels falling within each polygon -------------------------
# A pixel is included if its centre falls inside the polygon
df <- terra::extract(r_cwd, terra::vect(polys)) |>
  dplyr::mutate(
    site = factor(polys$site[ID], levels = c("Elder Creek", "Dry Creek"))
  ) |>
  dplyr::filter(!is.na(cwd_max))

readr::write_csv(df, here("data", "h3_cwd_validation.csv"))

# ---- Panel a: site map ------------------------------------------------------
# Polygons are back-transformed to WGS84 only for display on the satellite tiles.
polys_wgs <- sf::st_transform(polys, crs = 4326)

# Label anchor points: st_point_on_surface() guarantees a point inside the
# polygon even for concave, hand-drawn shapes
labels_wgs <- sf::st_point_on_surface(polys_wgs)

# Bounding box of both catchments plus a margin (metres, EPSG:5070) so the
# polygons are not glued to the panel edge, then to WGS84 for the tiles.
margin_m <- 3000
box <- sf::st_bbox(polys)
box["xmin"] <- box["xmin"] - margin_m
box["xmax"] <- box["xmax"] + margin_m
box["ymin"] <- box["ymin"] - margin_m
box["ymax"] <- box["ymax"] + margin_m

box_wgs <- sf::st_bbox(sf::st_transform(sf::st_as_sfc(box), 4326))
xmin <- box_wgs[["xmin"]]; xmax <- box_wgs[["xmax"]]
ymin <- box_wgs[["ymin"]]; ymax <- box_wgs[["ymax"]]

ext <- terra::ext(xmin, xmax, ymin, ymax)

# Vertical label nudge (map degrees), converted from ~1 cm on the saved
# figure using the y-extent and the panel height
fig_height_cm  <- panel_h_cm
deg_per_cm     <- (ymax - ymin) / fig_height_cm
nudge_y_labels <- 0.012 + 0.5 * deg_per_cm

tiles <- get_tiles(
  x        = ext,
  provider = "Esri.WorldImagery",
  zoom     = 13,
  crop     = TRUE,
  project  = FALSE
)

main_map <- ggplot() +
  geom_spatraster_rgb(data = tiles) +
  # Catchment outlines
  geom_sf(data = polys_wgs, fill = NA, colour = "red",
          linewidth = 0.4) +
  # Site labels next to the catchments
  geom_sf_text(data = labels_wgs, aes(label = site),
               colour = "white", size = 3, fontface = "bold",
               nudge_y = nudge_y_labels) +
  # visible gap between the axis lines and the map
  coord_sf(
    xlim = c(xmin, xmax),
    ylim = c(ymin, ymax),
    crs  = 4326
  ) +
  
  annotation_scale(
    location   = "bl",
    width_hint = 0.15,
    style      = "bar",
    bar_cols   = c("black", "white"),
    height     = grid::unit(0.12, "cm"),
    text_cex   = 0.8
  ) +
  
  annotation_north_arrow(
    location    = "br",
    which_north = "grid",
    style       = north_arrow_fancy_orienteering(
      fill     = c("white", "grey40"),
      line_col = "grey20",
      text_col = "white"
    ),
    height = unit(0.8, "cm"),
    width  = unit(0.8, "cm")
  ) +
  
  scale_x_continuous(breaks = scales::breaks_pretty(n = 3)) +
  scale_y_continuous(breaks = scales::breaks_pretty(n = 3)) +
  labs(
    x = "Longitude",
    y = "Latitude"
  ) +
  
  theme_classic(base_size = 13) +
  theme(
    axis.ticks        = element_line(colour = "grey30", linewidth = 0.4),
    axis.ticks.length = unit(0.15, "cm"),
    axis.text         = element_text(size = 8),
    # Rotated longitude labels take less horizontal space per label.
    # hjust = 1 keeps the label's end anchored under its tick mark.
    axis.text.x       = element_text(angle = 45, hjust = 1),
    axis.title        = element_text(size = 11),
    plot.title        = element_text(size = 14)
  )

# Attribution as a cowplot label in the lower right corner, same position
# and styling as on the focus-region figures
p_map <- ggdraw(main_map) +
  draw_label(
    "\u00a9 Esri World Imagery",
    x = 0.99, y = 0.01, hjust = 1, vjust = 0,
    size = 6, colour = "grey40"
  )

# ---- Panel b: boxplot -------------------------------------------------------
p_box <- ggplot(df, aes(x = site, y = cwd_max)) +
  geom_boxplot(fill = "grey70", outlier.size = 0.3, outlier.alpha = 0.2) +
  labs(
    x = NULL,
    y = expression(CWD[max] ~ "[mm]")
  ) +
  theme_classic() +
  theme(legend.position = "none")

# Add per-group n label.
p_box <- p_box + add_boxplot_n(df, "site", "cwd_max")

# ---- Combine and save -------------------------------------------------------
# rel_widths reproduce the panel widths the two plots were designed for.
# No align = : the map has a fixed aspect ratio and aligning the plot areas
# would rescale it.
fig <- cowplot::plot_grid(
  p_map, p_box,
  labels     = "auto",
  rel_widths = c(map_w_cm, box_w_cm)
)

print(fig)

save_fig(fig, "h3_elder_dry_with_map", width = map_w_cm + box_w_cm, height = panel_h_cm)